//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestMadeAstar.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TenantPersonnel
    {
        public int TenantId { get; set; }
        
        public string FirstName { get; set; }
        public string MiddleName { get; set; }
        public string LastName { get; set; }
        public string NickName { get; set; }
        public System.DateTime DOB { get; set; }
        public string Active { get; set; }
        public int GenderFk { get; set; }
        public string PrefixID { get; set; }
    
        public virtual Gender Gender { get; set; }
    }
}
